version: '2.3'
services:
    app:
        build: .
        container_name: lwm
        runtime: nvidia
        volumes:
            - .:/home
        tty: true
        ports:
            - "6006:6006"
